trigger:
- main

variables:
  imageName: tunnetcom/ai-sre-engine

stages:

- stage: BuildAndPush
  jobs:
  - job: build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        repository: $(imageName)
        dockerfile: Dockerfile
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: 'TunNetCom_Dockerhub_Connection'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - job: deploy
    pool: OnPremAgents
    steps:
 
    - script: |
        kubectl set image deployment/ai-sre-engine \
          engine=$(imageName):$(Build.BuildId) \
          -n ai-sre
      displayName: Update image